version: "2"

services:
  mongodb: 
    build: ./mongodb
    container_name: mongodb
    restart: always
    ports: 
      - "27017:27017"
  api: 
    build: ./api
    container_name: api
    restart: always
    ports: 
      - "6969:6969"
    volumes:
      - ./api:/usr/src/app
      #- /usr/src/app/node_modules
    links:
      - mongodb #Need to link to mongodb container to run same network
    depends_on:
      - mongodb