version: "2"

services:
  mongodb: 
    build: ./mongodb
    container_name: mongodb
    restart: always
    ports: 
      - "27017:27017"
  api: 
    build: ./api
    container_name: api
    restart: always
    ports: 
      - "6969:6969"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - mongodb